development:
  adapter: mysql2
  database: mediafranca
  username: root
  password: 1dvuvvdu
  host: localhost
  socket: /tmp/mysql.sock
  encoding: utf8
test:
  adapter: mysql2
  database: mediafranca
  username: root
  password: 1dvuvvdu
  host: localhost
  socket: /tmp/mysql.sock
  encoding: utf8
production:
  adapter: mysql2
  database: mediafranca
  username: root
  password: 1dvuvvdu
  host: localhost
  socket: /tmp/mysql.sock
  encoding: utf8